export const USER_ADD_EVENT = 'USER_ADD_EVENT';
export const USER_UPDATE_EVENT = 'USER_UPDATE_EVENT';
export const USER_DELETE_EVENT = 'USER_DELETE_EVENT';
export const USER_GET_EVENTS = 'USER_GET_EVENTS';