export const USER_ADD_NEW_PROFILE_PICTURE = 'USER_ADD_NEW_PROFILE_PICTURE';
export const USER_GET_PROFILE_PICTURE = 'USER_GET_PROFILE_PICTURE';

//User Changing Login settings:

export const USER_CHANGE_EMAIL_ADDRESS = 'USER_CHANGE_EMAIL_ADDRESS';
export const USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME';
export const USER_CHANGE_FIRSTNAME = 'USER_CHANGE_FIRSTNAME';
export const USER_CHANGE_LASTNAME = 'USER_CHANGE_LASTNAME';