//Protocol Variables:

export const USER_ADD_PROTOCOL = 'USER_ADD_PROTOCOL';
export const USER_DELETE_PROTOCOL = 'USER_DELETE_PROTOCOL';
export const USER_EDIT_NAME_PROTOCOL = 'USER_EDIT_NAME_PROTOCOL';
export const USER_GET_PROTOCOL = 'USER_GET_PROTOCOL';

//Collection Strains Variables:

export const USER_ADD_STRAIN_TO_COLLECTION = 'USER_ADD_STRAIN_TO_COLLECTION';
export const USER_EDIT_STRAIN_IN_COLLECTION = 'USER_EDIT_STRAIN_IN_COLLECTION';
export const USER_REMOVE_STRAIN_FROM_COLLECTION = 'USER_REMOVE_STRAIN_FROM_COLLECTION';
export const USER_GET_STRAINS_FROM_COLLECTION = 'USER_GET_STRAINS_FROM_COLLECTION';

export const USER_ADD_COLLECTION_DATA_TO_STRAIN = 'USER_ADD_COLLECTION_DATA_TO_STRAIN';
export const USER_ADD_COLLECTION_PARSED_DATA_TO_STRAIN = 'USER_ADD_COLLECTION_PARSED_DATA_TO_STRAIN';

export const USER_ADD_LACZ_DATA_TO_STRAIN = 'USER_ADD_LACZ_DATA_TO_STRAIN';