export enum SettingsActionType {
    //Grabbing user data
    USER_ADD_NEW_PROFILE_PICTURE = 'USER_ADD_NEW_PROFILE_PICTURE',
    USER_GET_PROFILE_PICTURE = 'USER_GET_PROFILE_PICTURE',

    //User Changing Login settings:

    USER_CHANGE_EMAIL_ADDRESS = 'USER_CHANGE_EMAIL_ADDRESS',
    USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME',
    USER_CHANGE_FIRSTNAME = 'USER_CHANGE_FIRSTNAME',
    USER_CHANGE_LASTNAME = 'USER_CHANGE_LASTNAME',
    USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
}
