//Light and Dark Themes:

export const lightTheme = {
    mainBody: '#f6f9fc',
    text: '#000022',
    background: '#E5E5E5',
    //Main Dashboard
    navAvatarBorder: '#293241',
    navBgColor: '#222444',
    navBorderColor: '3px solid #293241',
    navDetailUserName: '#141628',
    navDetailName: '#141628',
    navDetailEmail: '#141628',
    LogoDividerColor: '#293241',
    navIconColor: '#ffffff',
    navIconHoverColor: '#01348e',
    mdTodoBgColor: 'white',
    //MDsciCard
    sciCardMainContainerBG: 'white',
    headLineC: 'black',
    authorLineC: 'black',
    timeLineC: 'black',
    descLineC: 'black',
    //Messenger
    messengerContainerBGColor: '#f6f9fc',
    chatContainerBGColor: 'white',
    chatInputContainer: 'white',
    chatInputColor: '#293241',
    chatInputText: 'white',
    //ChatCard
    chatCardBGColor: 'white',
    chatCardTextColor: '#293241',
    //Calendar
    calendarContainerBGColor: '#f6f9fc',
    calendarSideBarContainerBG: '#293241',
    calendarChartBG: 'white',
    calendarTextC: 'black',
    //Bionotes
    bionotesContainerBGColor: '#f6f9fc',
    bionoteCardColor: 'white',
    bionoteTextColor: 'black',
    bionoteBorderColor: '1px solid white',
    //SciTools
    landingPageBGColor: '#f6f9fc',
    landingPageSecondaryHeader: '#293241',
    //lacZAssay
    lacZMainHeaderBG: '#293241',
    lacZSecondaryHeaderBG: '#293241',
    lacZStyledInputC: 'black',
    lacZStyledInputBG: 'white',
    lacZStyledInputBorder: '1px solid #ccc',
    //ProtocolCard
    PCMainCardContainerBG: 'white',
    PCCardHeaderC: '#293241',
    PCDelBtnC: 'rgb(127, 3, 0)',
    PCEditBtnC: 'rgb(0, 102, 0)',
    PCTimeC: '#293241',
    //Collection:
    ColMainContainerBG: '#f6f9fc',
    ColInputContainerBG: 'white',
    ColInputContainerBorderC: '1px solid white',
    ColInputMainHeader: '#293241',
    ColInputTimeLabel: '#293241',
    ColStrainInputBG: 'white',
    ColStrainInputC: 'black',
    ColStrainsContainerBG: 'white',
    ColStrainsContainerBorder: '1px solid white',
    ColStrainCardBG: 'white',
    ColStrainCardExistingCDataC: 'black',
    //lacZ
    lacZMainContainerBG: '#f6f9fc',
    lacZMainHeaderC: '#293241',
    lacZCardContainerBG: 'white',
    lacZCardInputHeaderBG: 'black',
    lacZChartFlexContainerBG: 'white',
    lacZChartCompareBG: '#f6f9fc',
    lacZCardRenderingContainerBG: 'white',
    //UserSettings
    settingsHeaderBG: 'white',
    settingsHeaderBorderBottomC: '#293241',
    settingsBackgroundContainer: '#f6f9fc',
    settingsMainHeaderTextC: '#293241',
    settingsMainContainerBG: 'white',
    settingsAvatarBorderC: 'white',
};

export const darkTheme = {
    mainBody: '#202345',
    text: '#ffffff',
    background: '#141628',
    //Main DashBoard
    navBgColor: '#222444',
    navAvatarBorder: 'white',
    navBorderColor: '1px solid black',
    navDetailUserName: 'white',
    navDetailName: 'white',
    navDetailEmail: 'white',
    LogoDividerColor: 'black',
    navIconColor: '#ffffff',
    navIconHoverColor: '#2f71e4',
    mdTodoBgColor: '#2d2f57',
    //MDsciCard
    sciCardMainContainerBG: '#2d2f57',
    headLineC: 'white',
    authorLineC: 'white',
    timeLineC: 'white',
    descLineC: 'white',
    //Messenger
    messengerContainerBGColor: '#141628',
    chatContainerBGColor: '#242746',
    chatInputContainer: '#242746',
    chatInputColor: 'white',
    chatInputText: '#242746',
    //ChatCard
    chatCardBGColor: '#242746',
    chatCardTextColor: 'white',
    //Calendar
    calendarContainerBGColor: '#141628',
    calendarSideBarContainerBG: '#242746',
    calendarChartBG: '#242746',
    calendarTextC: 'white',
    //Bionotes
    bionotesContainerBGColor: '#141628',
    bionoteCardColor: '#2d2f57',
    bionoteTextColor: 'white',
    bionoteBorderColor: '1px solid #293241',
    //SciTools
    landingPageBGColor: '#141628',
    landingPageSecondaryHeader: 'white',
    //lacZAssay
    lacZMainHeaderBG: 'white',
    lacZSecondaryHeaderBG: 'white',
    lacZStyledInputC: 'white',
    lacZStyledInputBG: '#2d2f57',
    lacZStyledInputBorder: '1px solid black',
    //ProtocolCard
    PCMainCardContainerBG: '#2d2f57',
    PCCardHeaderC: 'white',
    PCDelBtnC: 'rgb(155, 3, 1)',
    PCEditBtnC: 'rgb(1, 130, 1)',
    PCTimeC: 'white',
    //Collection:
    ColMainContainerBG: '#141628',
    ColInputContainerBG: '#242746',
    ColInputContainerBorderC: '1px solid #2d2f57',
    ColInputMainHeader: 'white',
    ColInputTimeLabel: 'white',
    ColStrainInputBG: '#293241',
    ColStrainInputC: 'white',
    ColStrainsContainerBG: '#242746',
    ColStrainsContainerBorder: '1px solid#2d2f57',
    ColStrainCardBG: '#242746',
    ColStrainCardExistingCDataC: 'black',
    //LacZ
    lacZMainContainerBG: '#141628',
    lacZCardInputHeaderBG: 'white',
    lacZMainHeaderC: 'white',
    lacZCardContainerBG: '#2d2f57',
    lacZChartFlexContainerBG: '#2d2f57',
    lacZChartCompareBG: '#141628',
    lacZCardRenderingContainerBG: '#2d2f57',
    //UserSettings
    settingsHeaderBG: '#222444',
    settingsHeaderBorderBottomC: '#222444',
    settingsBackgroundContainer: '#141628',
    settingsMainHeaderTextC: 'white',
    settingsMainContainerBG: 'white',
    settingsAvatarBorderC: '#242746',
};
