export enum NotebookActionType {
    USER_ADD_NOTE = 'USER_ADD_NOTE',
    USER_UPDATE_NOTE = 'USER_UPDATE_NOTE',
    USER_DELETE_NOTE = 'USER_DELETE_NOTE',
    USER_GET_NOTEBOOK = 'USER_GET_NOTEBOOK',
    USER_ADD_FOLDER = 'USER_ADD_FOLDER',
    USER_DELETE_FOLDER = 'USER_DELETE_FOLDER',
    USER_RENAME_FOLDER = 'USER_RENAME_FOLDER',
}
