export enum LacZActionType {
    //Protocol Variables:
    USER_ADD_PROTOCOL = 'USER_ADD_PROTOCOL',
    USER_DELETE_PROTOCOL = 'USER_DELETE_PROTOCOL',
    USER_EDIT_NAME_PROTOCOL = 'USER_EDIT_NAME_PROTOCOL',
    USER_GET_PROTOCOL = 'USER_GET_PROTOCOL',

    //Collection Strains Variables:

    USER_ADD_STRAIN_TO_COLLECTION = 'USER_ADD_STRAIN_TO_COLLECTION',
    USER_EDIT_STRAIN_IN_COLLECTION = 'USER_EDIT_STRAIN_IN_COLLECTION',
    USER_REMOVE_STRAIN_FROM_COLLECTION = 'USER_REMOVE_STRAIN_FROM_COLLECTION',
    USER_GET_STRAINS_FROM_COLLECTION = 'USER_GET_STRAINS_FROM_COLLECTION',

    USER_ADD_COLLECTION_DATA_TO_STRAIN = 'USER_ADD_COLLECTION_DATA_TO_STRAIN',
    USER_ADD_COLLECTION_PARSED_DATA_TO_STRAIN = 'USER_ADD_COLLECTION_PARSED_DATA_TO_STRAIN',

    USER_ADD_LACZ_DATA_TO_STRAIN = 'USER_ADD_LACZ_DATA_TO_STRAIN',
    USER_ADD_BGAL_DATA_TO_STRAIN = 'USER_ADD_BGAL_DATA_TO_STRAIN',
}
