export enum BionoteActionType {
    USER_ADD_BIONOTE = 'USER_ADD_BIONOTE',
    USER_UPDATE_BIONOTE = 'USER_UPDATE_BIONOTE',
    USER_DELETE_BIONOTE = 'USER_DELETE_BIONOTE',
    USER_GET_BIONOTES = 'USER_GET_BIONOTES',
}
