export enum CalendarActionType {
    USER_ADD_EVENT = 'USER_ADD_EVENT',
    USER_UPDATE_EVENT = 'USER_UPDATE_EVENT',
    USER_DELETE_EVENT = 'USER_DELETE_EVENT',
    USER_GET_EVENTS = 'USER_GET_EVENTS',
}
