export const USER_ADD_BIONOTE = 'USER_ADD_BIONOTE';
export const USER_UPDATE_BIONOTE = 'USER_UPDATE_BIONOTE';
export const USER_DELETE_BIONOTE = 'USER_DELETE_BIONOTE';
export const USER_GET_BIONOTES = 'USER_GET_BIONOTES';